---
- name: Download Wordpress
  ansible.builtin.get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  ansible.builtin.unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes
    
- name: Set ownership of WordPress files for CentOs
  when: ansible_os_family == "RedHat"
  ansible.builtin.file:
    name: /var/www/html/wordpress
    owner: apache
    group: apache
    mode: '0755'
    recurse: yes

- name: Set ownership of WordPress files for Ubuntu
  when: ansible_os_family == "Debian"
  ansible.builtin.file:
    name: /var/www/html/wordpress
    owner: www-data
    group: www-data
    mode: '0755'
    recurse: yes

- name: Configure Apache for WordPress (CentOS)
  when: ansible_os_family == "RedHat"
  template:
    src: wordpressCentOs.conf.j2
    dest: /etc/httpd/conf.d/wordpress.conf


- name: Configure Apache for WordPress (Ubuntu)
  when: ansible_os_family == "Debian"
  template:
    src: wordpress.confUbuntu.j2
    dest: /etc/apache2/sites-available/wordpress.conf

- name: Enable WordPress site (Ubuntu)
  when: ansible_os_family == "Debian"
  ansible.builtin.command:
    cmd: a2ensite wordpress
  

- name: Enable rewrite module (Ubuntu)
  when: ansible_os_family == "Debian"
  ansible.builtin.command:
    cmd: a2enmod rewrite
  

- name: Restart Apache (Ubuntu)
  when: ansible_os_family == "Debian"
  ansible.builtin.service:
    name: apache2
    state: restarted
  

- name: Restart Apache (CentOS)
  when: ansible_os_family == "RedHat"
  ansible.builtin.service:
    name: httpd
    state: restarted
  


    